---
- name: Set Redis state fact
  ansible.builtin.set_fact:
    redis_state: "{{ 'present' if redis_enabled else 'absent' }}"

- name: Build Redis
  include_role:
    name: nix_build
  vars:
    nix_build_attr: nixpkgs#redis
    nix_build_out: /opt/redis
    nix_build_state: "{{ redis_state }}"

- name: Create s6 service
  include_role:
    name: s6_service
  vars:
    s6_service_name: redis
    s6_service_command: "exec /opt/redis/bin/redis-server /etc/redis/redis.conf"
    s6_service_pre_exec: |
      backtick -n SOCKET_DIR { dirname {{ redis_socket }} }

      importas SOCKET_DIR SOCKET_DIR
      foreground { mkdir -m 750 -p ${SOCKET_DIR} }
      foreground { chown {{ redis_user }}:{{ redis_group }} ${SOCKET_DIR} }
    s6_service_user_name: "{{ redis_user }}"
    s6_service_env:
      LANG: c
      LC_ALL: C
    s6_service_state: "{{ redis_state }}"

- name: Ensure Redis config directories exist
  when: redis_enabled
  ansible.builtin.file:
    path: "/etc/redis"
    state: directory
    owner: "{{ redis_user }}"
    group: "{{ redis_group }}"
    recurse: true

- name: Create redis.conf
  when: redis_enabled
  ansible.builtin.template:
    src: redis.conf
    dest: /etc/redis/
    mode: "0644"

