---
- name: Set caddy state fact
  ansible.builtin.set_fact:
    caddy_state: "{{ 'present' if caddy_enabled else 'absent' }}"

- name: Install caddy package
  ansible.builtin.apt:
    name: caddy
    state: "{{ caddy_state }}"

- name: Create s6 service
  include_role:
    name: s6_service
  vars:
    s6_service_name: caddy
    s6_service_command: caddy run --config /etc/caddy/Caddyfile --adapter caddyfile
    s6_service_user_name: "{{ caddy_user }}"
    s6_service_state: "{{ caddy_state }}"

- name: Create caddy directories
  when: caddy_enabled
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ caddy_user }}"
    group: "{{ caddy_group }}"
  loop:
    - "/etc/caddy"

- name: Create Caddyfile
  when: caddy_enabled
  template:
    src: Caddyfile
    dest: /etc/caddy/
    mode: "0644"

