---
- name: Set caddy state fact
  ansible.builtin.set_fact:
    caddy_state: "{{ 'present' if caddy_enabled else 'absent' }}"

- name: Build caddy
  ansible.builtin.include_role:
    name: nix_build
  vars:
    nix_build_attr: "{{ caddy_package }}"
    nix_build_out: "{{ caddy_package_path }}"
    nix_build_state: "{{ caddy_state }}"

- name: Create s6 service
  ansible.builtin.include_role:
    name: s6_service
  vars:
    s6_service_name: caddy
    s6_service_command: "{{ caddy_package_path }}/bin/caddy run --config /etc/caddy/Caddyfile --adapter caddyfile"
    s6_service_user_name: "{{ caddy_user }}"
    s6_service_state: "{{ caddy_state }}"
    s6_service_env: "{{ caddy_env }}"

- name: Ensure caddy config directories exist
  when: caddy_enabled
  ansible.builtin.file:
    path: "/etc/caddy"
    state: directory
    owner: "{{ caddy_user }}"
    group: "{{ caddy_group }}"
    recurse: true

- name: Create Caddyfile
  when: caddy_enabled
  ansible.builtin.template:
    src: Caddyfile
    dest: /etc/caddy/
    mode: "0644"
