---
cloudflared_enabled: false
cloudflared_user: cloudflared
cloudflared_group: cloudflared
cloudflared_tunnel: 80415f05-21c3-4e0e-9b59-2e155b5f3cb3
cloudflared_domain: "700457.xyz"
cloudflared_subdomains:
  - gist
