---
- name: Set Navidrome state fact
  ansible.builtin.set_fact:
    navidrome_state: "{{ 'present' if navidrome_enabled else 'absent' }}"

- name: Build Navidrome
  include_role:
    name: nix_build
  vars:
    nix_build_attr: nixpkgs#navidrome
    nix_build_out: /opt/navidrome
    nix_build_state: "{{ navidrome_state }}"

- name: Create s6 service
  include_role:
    name: s6_service
  vars:
    s6_service_name: navidrome
    s6_service_command: 'exec /opt/navidrome/bin/navidrome --configfile "/etc/navidrome/navidrome.toml"'
    s6_service_user_name: "{{ navidrome_user }}"
    s6_service_user_group: "{{ navidrome_group }}"
    s6_service_state: "{{ navidrome_state }}"

- name: Ensure Navidrome directories exist
  when: navidrome_enabled
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ navidrome_user }}"
    group: "{{ navidrome_group }}"
    recurse: true
  loop:
    - /etc/navidrome
    - "{{ navidrome_dir }}"
    - "{{ navidrome_music_dir }}"
    - "{{ navidrome_data_dir }}"
    - "{{ navidrome_cache_dir }}"
    
- name: Create navidrome.toml
  when: navidrome_enabled
  template:
    src: navidrome.toml
    dest: /etc/navidrome/
    owner: "{{ navidrome_user }}"
    group: "{{ navidrome_group }}"
    mode: "0644"
