---
paperless_ngx_enabled: false
paperless_ngx_user: paperless
paperless_ngx_user_groups: redis
paperless_ngx_port: "3002"

paperless_ngx_env: # https://docs.paperless-ngx.com/configuration
  PAPERLESS_SECRET_KEY: "__CHANGE_ME__"

paperless_ngx_package: nixpkgs/21e032ff95225fb81164a2b2b696c5f6841fcb62#paperless-ngx
paperless_ngx_package_path: /opt/paperless
