---
- name: Set tailscaled state fact
  ansible.builtin.set_fact:
    tailscaled_state: "{{ 'present' if tailscaled_enabled else 'absent' }}"

- name: Create s6 service
  include_role:
    name: s6_service
  vars:
    s6_service_name: tailscaled
    s6_service_command: 'exec {{ tailscale_package_path }}/bin/tailscaled'
    s6_service_create_user: false
    s6_service_state: "{{ tailscaled_state }}"
