---
- name: Set Paperless-ngx state fact
  ansible.builtin.set_fact:
    paperless_ngx_state: "{{ 'present' if paperless_ngx_enabled else 'absent' }}"

- name: Build Paperless-ngx
  ansible.builtin.include_role:
    name: nix_build
  vars:
    nix_build_attr: "{{ paperless_ngx_package }}"
    nix_build_out: "{{ paperless_ngx_package_path }}"
    nix_build_state: "{{ paperless_ngx_state }}"

- name: Create s6 services
  ansible.builtin.include_role:
    name: s6_service
  vars:
    s6_service_name: "{{ service.name }}"
    s6_service_state: "{{ paperless_ngx_state }}"
    s6_service_command: "{{ service.command }}"
    s6_service_user_name: "{{ paperless_ngx_user }}"
    s6_service_user_groups: "{{ paperless_ngx_user_groups }}"
    s6_service_env: "{{ paperless_ngx_env_default | combine(paperless_ngx_env, recursive=true) }}"
    s6_service_dependencies: [redis]
  loop: "{{ paperless_ngx_services }}"
  loop_control:
    loop_var: service
