---
- name: Set restic rest-server state fact
  ansible.builtin.set_fact:
    restic_rest_server_state: "{{ 'present' if restic_rest_server_enabled else 'absent' }}"

- name: Build restic rest-server
  include_role:
    name: nix_build
  vars:
    nix_build_attr: nixpkgs#restic-rest-server
    nix_build_out: /opt/restic_rest_server
    nix_build_state: "{{ restic_rest_server_state }}"

- name: Create s6 service
  include_role:
    name: s6_service
  vars:
    s6_service_name: restic_rest_server
    s6_service_command: |
      exec /opt/restic_rest_server/bin/rest-server \
        --listen "127.0.0.1:{{ restic_rest_server_port }}" \
        --log - \
        --path {{ restic_rest_server_data_dir }}
        --htpasswd-file /etc/restic_rest_server/.htpasswd
        --private-repos
    s6_service_user_name: "{{ restic_rest_server_user }}"
    s6_service_state: "{{ restic_rest_server_state }}"

- name: Ensure restic rest-server config directory exists
  when: restic_rest_server_enabled
  file:
    path: "/etc/restic_rest_server"
    state: directory
    owner: "{{ restic_rest_server_user }}"
    group: "{{ restic_rest_server_group }}"
    recurse: true

- name: Add users to .htpasswd
  when: restic_rest_server_enabled
  community.general.htpasswd:
    path: /etc/restic_rest_server/.htpasswd
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    hash_scheme: bcrypt
    owner: "{{ restic_rest_server_user }}"
    group: "{{ restic_rest_server_group }}"
    mode: "0640"
  loop: "{{ restic_rest_server_htpasswd_users }}"
  no_log: true

