---
argument_specs:
  main:
    short_description: Configure and deploy Paperless-ngx
    description:
      - Builds Paperless-ngx from nixpkgs (pinned commit) and creates multiple s6 services (web, worker, beat, consumer).
    options:
      paperless_ngx_enabled:
        type: bool
        required: false
        default: false
        description: Enable Paperless-ngx
      paperless_ngx_user:
        type: str
        required: false
        default: paperless
        description: System user for Paperless-ngx services
      paperless_ngx_user_groups:
        type: str
        required: false
        default: redis
        description: Supplementary groups for the Paperless-ngx user
      paperless_ngx_env:
        type: dict
        required: false
        description: >-
          Environment variables for Paperless-ngx configuration. See
          [`defaults/main.yml#L7-L8`](https://github.com/lightly-toasted/phomelab/blob/main/roles/paperless_ngx/defaults/main.yml#L7-L8)
          and the [upstream documentation](https://docs.paperless-ngx.com/configuration)
          for an example.
      paperless_ngx_port:
        type: str
        required: false
        default: "3002"
        description: TCP port for the Paperless-ngx web service
      paperless_ngx_package:
        type: str
        required: false
        default: nixpkgs/21e032ff95225fb81164a2b2b696c5f6841fcb62#paperless-ngx
        description: Nix package attribute for Paperless-ngx
      paperless_ngx_package_path:
        type: path
        required: false
        default: /opt/paperless
        description: Nix build output path for Paperless-ngx
