---
- name: Set paperless-gpt state fact
  ansible.builtin.set_fact:
    paperless_gpt_state: "{{ 'present' if paperless_gpt_enabled else 'absent' }}"

- name: Build paperless-gpt
  ansible.builtin.include_role:
    name: nix_build
  vars:
    nix_build_attr: github:lightly-toasted/phomelab/c1644f0c7cd8ea06d44249da68b98dc752d8420b#paperless-gpt
    nix_build_out: /opt/paperless-gpt
    nix_build_state: "{{ paperless_gpt_state }}"

- name: Create s6 service
  ansible.builtin.include_role:
    name: s6_service
  vars:
    s6_service_name: paperless-gpt
    s6_service_user_name: "{{ paperless_gpt_user }}"
    s6_service_user_group: "{{ paperless_gpt_group }}"
    s6_service_command: "exec /opt/paperless-gpt/bin/paperless-gpt"
    s6_service_env: "{{ paperless_gpt_env }}"
    s6_service_state: "{{ paperless_gpt_state }}"
    s6_service_workdir: "{{ paperless_gpt_data_dir }}"

- name: Ensure paperless-gpt directories exist
  when: paperless_gpt_enabled
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ paperless_gpt_user }}"
    group: "{{ paperless_gpt_group }}"
    recurse: true
  loop:
    - "{{ paperless_gpt_data_dir }}"
    - "{{ paperless_gpt_data_dir }}/default_prompts"
    - "{{ paperless_gpt_data_dir }}/prompts"

- name: Ensure default_prompts exist
  when: paperless_gpt_enabled
  ansible.builtin.copy:
    dest: "{{ paperless_gpt_data_dir }}/default_prompts/{{ item.key }}"
    content: "{{ item.value }}"
    owner: "{{ paperless_gpt_user }}"
    group: "{{ paperless_gpt_group }}"
    mode: "0644"
  loop: "{{ paperless_gpt_prompts | dict2items }}"

- name: Ensure prompts exist
  when: paperless_gpt_enabled
  ansible.builtin.copy:
    dest: "{{ paperless_gpt_data_dir }}/prompts/{{ item.key }}"
    content: "{{ item.value }}"
    owner: "{{ paperless_gpt_user }}"
    group: "{{ paperless_gpt_group }}"
    mode: "0644"
  loop: "{{ paperless_gpt_prompts | dict2items }}"
