---
- name: Set cloudflared state fact
  ansible.builtin.set_fact:
    cloudflared_state: "{{ 'present' if cloudflared_enabled else 'absent' }}"

- name: Build cloudflared
  include_role:
    name: nix_build
  vars:
    nix_build_attr: nixpkgs#cloudflared
    nix_build_out: /opt/cloudflared
    nix_build_state: "{{ cloudflared_state }}"

- name: Create s6 service
  include_role:
    name: s6_service
  vars:
    s6_service_name: cloudflared
    s6_service_command: "exec /opt/cloudflared/bin/cloudflared tunnel run"
    s6_service_user_name: "{{ cloudflared_user }}"
    s6_service_state: "{{ cloudflared_state }}"

- name: Ensure cloudflared directories exist
  when: cloudflared_enabled
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ cloudflared_user }}"
    group: "{{ cloudflared_group }}"
    recurse: true
  loop:
    - "/var/lib/cloudflared"
    - "/etc/cloudflared"

- name: Copy cloudflared credentials file
  when: cloudflared_enabled
  copy:
    dest: "/etc/cloudflared/{{ cloudflared_tunnel }}.json"
    content: "{{ cloudflared_credentials }}"
    mode: "0644"

- name: Create config.yml
  when: cloudflared_enabled
  copy:
    dest: /etc/cloudflared/config.yml
    content: "{{ cloudflared_tunnel_config | combine(cloudflared_config, recursive=true) | to_nice_yaml }}"
    mode: "0644"
  
